import { z } from "zod";
import { extendZodWithOpenApi } from "@asteasolutions/zod-to-openapi";

extendZodWithOpenApi(z);

export const CampaignSchema = z.object({
    id: z.string().uuid().openapi({
        description: "The unique identifier of the campaign.",
        example: "ceaef6d9-767e-49aa-a6ab-46c02aa79604",
    }),
    created_at: z.string().datetime().openapi({
        description: "Timestamp when the campaign was created.",
        example: "2021-11-24T06:31:06.672Z",
    }),
    updated_at: z.string().datetime().openapi({
        description: "Timestamp when the campaign was last updated.",
        example: "2022-02-22T23:17:55.119Z",
    }),
    name: z.string().openapi({
        description: "The name of the campaign.",
        example: "Best Friends of Rewardful",
    }),
    url: z.string().url().openapi({
        description: "The URL associated with the campaign.",
        example: "https://rewardful.com/",
    }),
    private: z.boolean().openapi({
        description: "Indicates if the campaign is private.",
        example: false,
    }),
    private_tokens: z.boolean().openapi({
        description: "Indicates if the campaign uses private tokens.",
        example: false,
    }),
    commission_amount_cents: z.number().nullable().optional().openapi({
        description: "The fixed commission amount in cents, if applicable.",
        example: null,
    }),
    commission_amount_currency: z.string().nullable().optional().openapi({
        description: "The currency for the fixed commission amount.",
        example: null,
    }),
    minimum_payout_cents: z.number().int().openapi({
        description: "The minimum payout amount in cents.",
        example: 0,
    }),
    max_commission_period_months: z.number().nullable().optional().openapi({
        description: "The maximum period in months for commissions to be paid, if applicable.",
        example: null,
    }),
    max_commissions: z.number().nullable().optional().openapi({
        description: "The maximum number of commissions allowed for the campaign, if applicable.",
        example: null,
    }),
    days_before_referrals_expire: z.number().int().openapi({
        description: "Number of days before referrals expire.",
        example: 30,
    }),
    days_until_commissions_are_due: z.number().int().openapi({
        description: "Number of days until commissions become due.",
        example: 30,
    }),
    affiliate_dashboard_text: z.string().openapi({
        description: "Text displayed on the affiliate dashboard for this campaign.",
        example: "",
    }),
    custom_reward_description: z.string().openapi({
        description: "Custom description for the reward associated with the campaign.",
        example: "",
    }),
    welcome_text: z.string().openapi({
        description: "Welcome text for affiliates in the campaign.",
        example: "",
    }),
    customers_visible_to_affiliates: z.boolean().openapi({
        description: "Indicates if customers are visible to affiliates.",
        example: false,
    }),
    sale_description_visible_to_affiliates: z.boolean().openapi({
        description: "Indicates if the sale description is visible to affiliates.",
        example: true,
    }),
    parameter_type: z.enum(["query", "hash", "path"]).openapi({
        description: "Parameter type used by the campaign.",
        example: "query",
    }),
    stripe_coupon_id: z.string().nullable().optional().openapi({
        description: "The Stripe coupon ID associated with the campaign, if applicable.",
        example: "jo45MTj3",
    }),
    default: z.boolean().openapi({
        description: "Indicates if this is the default campaign.",
        example: false,
    }),
    reward_type: z.enum(["percent", "flat"]).openapi({
        description: "Type of reward for the campaign, either a percentage or a flat amount.",
        example: "percent",
    }),
    commission_percent: z.number().nullable().optional().openapi({
        description: "Commission percentage if the reward type is 'percent'.",
        example: 30.0,
    }),
    minimum_payout_currency: z.string().openapi({
        description: "Currency for the minimum payout amount.",
        example: "USD",
    }),
    visitors: z.number().int().openapi({
        description: "The number of visitors associated with the campaign.",
        example: 150,
    }),
    leads: z.number().int().openapi({
        description: "The number of leads generated by the campaign.",
        example: 39,
    }),
    conversions: z.number().int().openapi({
        description: "The number of conversions generated by the campaign.",
        example: 7,
    }),
    affiliates: z.number().int().openapi({
        description: "The number of affiliates participating in the campaign.",
        example: 12,
    }),
}).openapi("Campaign");
