import { z } from "zod";
import { extendZodWithOpenApi } from "@asteasolutions/zod-to-openapi";
import {AffiliateSchema, LinkSchema} from "../affiliate/schema";

extendZodWithOpenApi(z);

// Define schemas for nested objects within Referral

const CustomerSchema = z.object({
    id: z.string().openapi({
        description: "The unique identifier for the customer on the platform.",
        example: "cus_ABC123",
    }),
    name: z.string().openapi({
        description: "The customer's full name.",
        example: "Fred Durst",
    }),
    email: z.string().email().openapi({
        description: "The customer's email address.",
        example: "fred@example.com",
    }),
    platform: z.string().openapi({
        description: "The platform associated with this customer (e.g., Stripe).",
        example: "stripe",
    }),
}).openapi("Customer");

export const ReferralSchema = z.object({
    id: z.string().uuid().openapi({
        description: "The unique identifier for the referral.",
        example: "e523da29-6157-4aac-b4b5-05b3b7b14fb6",
    }),
    link: LinkSchema,
    visits: z.number().int().openapi({
        description: "The number of visits generated by the referral.",
        example: 42,
    }),
    customer: CustomerSchema,
    affiliate: AffiliateSchema,
    created_at: z.string().datetime().openapi({
        description: "Timestamp when the referral was created.",
        example: "2020-04-27T00:34:28.448Z",
    }),
    became_lead_at: z.string().datetime().nullable().openapi({
        description: "Timestamp when the referral became a lead.",
        example: "2020-04-27T00:36:28.448Z",
    }),
    became_conversion_at: z.string().datetime().nullable().openapi({
        description: "Timestamp when the referral became a conversion.",
        example: "2020-04-27T00:38:28.448Z",
    }),
    expires_at: z.string().datetime().nullable().openapi({
        description: "Expiration timestamp of the referral.",
        example: "2020-06-26T00:34:28.448Z",
    }),
    updated_at: z.string().datetime().openapi({
        description: "Timestamp when the referral was last updated.",
        example: "2020-04-27T00:38:28.448Z",
    }),
    deactivated_at: z.string().datetime().nullable().openapi({
        description: "Timestamp when the referral was deactivated, if applicable.",
        example: null,
    }),
    conversion_state: z.enum(["conversion", "lead", "visitor"]).openapi({
        description: "The current state of the referral, indicating if it is a conversion, lead, or visitor.",
        example: "conversion",
    }),
    stripe_account_id: z.string().nullable().openapi({
        description: "The Stripe account ID associated with the referral.",
        example: "acct_ABC123",
    }),
    stripe_customer_id: z.string().nullable().openapi({
        description: "The Stripe customer ID associated with the referral.",
        example: "cus_ABC123",
    }),
}).openapi("Referral");
